#docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker \
# -v $PWD:/apprun -w /apprun docker/compose:1.13.0 build

#https://hub.docker.com/r/docker/compose/tags/
# export CHSCALE=2 FFSCALE=4
# echo "PRIVATE_REGISTRY=192.168.6.17" > ".env"
# echo "SUM_OF_CHSCALE_AND_FFSCALE=$((CHSCALE+FFSCALE))" >> ".env"
# echo "GRID_VERSION=${GRID_VERSION}" >> ".env"
# docker run --rm -it docker/compose:1.13.0 up -d --scale firefox=${FFSCALE} --scale chrome=${CHSCALE}

#Or in versions <1.13 use scale command after starting services
# docker run --rm -it docker/compose:1.11.1 up -d
# docker run --rm -it docker/compose:1.11.1 scale firefox=4 chrome=2
#NOTE: context path is relative to this compose file
version: '2.0'

services:
  hub:
    build:
      context: .
      dockerfile: ./Dockerfile.hub
    image: "${PRIVATE_REGISTRY}bravo/japphub${GRID_VERSION}"
    network_mode: "bridge"
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSIONS=${SUM_OF_CHSCALE_AND_FFSCALE}
#      - GRID_DEBUG=true

  #https://github.com/jessfraz/dockerfiles/blob/master/chrome/stable/Dockerfile
  chrome:
    build:
      context: .
      dockerfile: ./Dockerfile.chrome
    image: "${PRIVATE_REGISTRY}bravo/jappchrome${GRID_VERSION}"
    network_mode: "bridge"
    volumes:
      - "/dev/urandom:/dev/random"
      - "/dev/shm:/dev/shm"
    links:
      - hub
    depends_on:
      - hub
#    security_opt:
#      - seccomp:./seccomp-chrome.json
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
#      - NODE_NDEBUG=true
      #- HTTP_PROXY=http://192.168.0.18:8081/

  firefox:
    build:
      context: .
      dockerfile: ./Dockerfile.firefox
    image: "${PRIVATE_REGISTRY}bravo/jappfirefox${GRID_VERSION}"
    network_mode: "bridge"
    volumes:
      - "/dev/urandom:/dev/random"
    links:
      - hub
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
#      - NODE_NDEBUG=true
